name: 03-basics-events-filter.yml

on:
#  push :
#    branches:
#      - master
#      - main

  pull_request:
    types: [closed , reopened ]

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "hello world"
