name: 03-basics-events-filter.yml

on:

  #  pull_request:
  #    types: [closed , reopened ]
  #    branches-ignore:
  #      - 02_basics-events


  push :
#    paths:
#      - 'routes/*.php'
#      - 'routes/**.php'
#    branches:
#      - master
#      - main

#    tags:
#      - v2

#    tags-ignore:
#      -


jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "hello world"
