name: 05-basics-events-schudle.yml

on:
  schedule:
    - cron: "15 4,5 * * *"

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "hello world"
