name: 06-basics-contexts.yml
run-name: ${{github.actor}} explains context - try number ${{github.run_number}}
on:
  workflow_dispatch:


jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        # run: echo "hello world"
        # run: echo ${{github}}
        # run: echo ${{github.actor}}
        run: echo ${{toJson(github)}}
        
        
        

