name: 07-basics-conditions.yml

on:
  pull_request:
    types:
      - closed

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Print Hello World
        run: echo "hello world"

      - name: Print Hello World Again
        if: github.event.pull_request.changed_files > 1
        run: echo "testing the condition"
