name: 08-basics-variables.yml
run-name: ${{github.actor}} explain env variables - try number ${{github.run_number}}

on:
  workflow_dispatch:


jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "hello world"

