name: 09-basics-configuration-variables.yml
run-name: ${{github.actor}} explains configration variables - try number ${{github.run_number}}

on:
  workflow_dispatch:


jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print configration variable
        run: echo ${{vars.MY_VARIABLE}}

      - name: print secret variable
        run: echo ${{secrets.MY_CREDENTIAL_PASSWORD}}

      - name: print default variables
        run: env      
