name: 11-basics-expressions.yml
run-name: ${{github.actor}} explaining expressions - try number ${{github.run_number}}

env:
  RUN_NUMBER: ${{github.run_number > 1 && 'Greater Than One' || 'Less Than One'}}
  TESTING_VALUE: ${{contains('hello wolrd' , 'wor')}}

on:
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        # run: echo ${{env.RUN_NUMBER}}
        run: exit 1 

      - name: print testing value
        if: success()
        run: echo ${{env.TESTING_VALUE}}

      - name: testing the expression
        if: always()
        run: echo "testing"



        
     
