name: 13-basics-needs.yml

run-name: ${{github.actor}} explaining needs - try number ${{github.run_number}}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build dependencies
        run: exit 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test dependencies
        run: echo "test dependencies"

  deploy:
    needs: [build , test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy dependencies
        run: echo "deploy dependencies"
