name: 14-basics-matrix.yml

run-name: ${{github.actor}} explains matrix - try number ${{github.run_number}}

on:
  workflow_dispatch:


jobs:
  Build:
    runs-on: ${{matrix.php}}
    strategy:
      matrix:
        php: [8.2 . 8.3]
        
    steps:
      - name: build project
        run: echo "build project"

