name: 15-basics-runners.yml

run-name: ${{github.actor}} explain env variables - try number ${{github.run_number}}

on:
  workflow_dispatch:


jobs:
  print-hello-world:
    runs-on: [self-hosted,Windows,X64,runner 1]
    steps:
      - name: Print Hello World
        run: echo "hello world"


