name: 16-basics-marketplace.yml

run-name: ${{github.actor}} explaining marketplace - try number ${{github.run_number}}

on:
  workflow_dispatch:


jobs:
  php_versions:
    runs-on: ubuntu-latest
    steps:
      - name: setup php version 7.2 
        uses: nanasess/setup-php@v4
        with:
          php-version: '7.2'

      - name: check php version
        run: php -v
