name: 17-basics-containers.yml

run-name: ${{github.actor}} explaining Containers - try number ${{github.run_number}}

on:
  workflow_dispatch:


jobs:
  php-versions:
    runs-on: ubuntu-latest

    container:
      image: php:7.2
      
    steps:
      - name: check php version
        run: php -v 
