name: 20-basics-custom-actions.yml

run-name: ${{github.actor}} explaining custom action - try number ${{github.run_number}}

on:
  workflow_dispatch:


jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v6.0.3
          
       - name: print hello world
         uses: ./.github/actions/print-hello-world
