name: 21-basics-custom-actions-2.yml

run-name: ${{github.actor}} explaining custom action 2 - try number ${{github.run_number}}

on:
  workflow_dispatch:


jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

        
      - name: print hello world
        uses: ./.github/actions/print-hello-world
