name: Example 01 - Commenting On PR
run-name: Example 01 - Commenting On PR

on:
  pull_request:
    types:
      - closed

jobs:
  comment-on-pr-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.3

      - name: Comment On Pr
        run: gh pr comment 13 --body "we will not accept your pr , check your code again"
        env:
          GH_TOKEN : ${{secrets.GITHUB_TOKEN}}



