name: Example 02 - Code Formatting with Laravel Pint
run-name: Example 02 - Code Formatting with Laravel Pint

on:
  push:
    branches:
      - master

jobs:
  run-pint-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.3

      - name: Run Laravel Pint
        run: ./vendor/bin/pint

      - name: Commit changes back
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add .

          git diff --cached --quiet || git commit -m "style: apply Laravel Pint formatting"

          git push
